version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_container
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis_container
    volumes:
      - redis_data:/data

  app:
    container_name: video_hosting
    image: back_app:v1
    env_file:
      - .env-prod
    ports:
      - 7070:8000
    depends_on:
      - db
      - redis

  celery:
    image: celery_app:v1
    container_name: celery_container
    env_file:
      - .env-prod
    depends_on:
      - redis

volumes:
  db_data:
  redis_data: