"""add subscription model

Revision ID: 0570a7e1c080
Revises: 5c6e365765e8
Create Date: 2023-05-28 21:04:04.448916

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0570a7e1c080'
down_revision = '5c6e365765e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('subscriber', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('subscribed', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['subscribed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscriber'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subscriber', 'subscribed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
