"""add viewer fingerprint to view model

Revision ID: 0740ccfde431
Revises: 9eab491449bd
Create Date: 2023-06-07 00:12:30.993860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0740ccfde431'
down_revision = '9eab491449bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('fingerprint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view', 'fingerprint')
    # ### end Alembic commands ###
