"""add like cascade delete

Revision ID: 29e876758f32
Revises: 7e98120060de
Create Date: 2023-06-05 20:55:47.775081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e876758f32'
down_revision = '7e98120060de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_video_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_video_id_fkey', 'like', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
