"""add admin

Revision ID: 4bd25fb493e7
Revises: 515c9c701a14
Create Date: 2023-06-17 22:07:06.980380

"""
import datetime

from alembic import op
import sqlalchemy as sa
from fastapi_users.password import PasswordHelper
from sqlalchemy import table, column, String, TIMESTAMP, UUID, Boolean

from src.config import ADMIN_PASSWORD
from src.subscription.models import Subscription
from src.user.models import User

# revision identifiers, used by Alembic.
revision = '4bd25fb493e7'
down_revision = '515c9c701a14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    user_table = table(
        "user",
        column("id", UUID),
        column("name", String),
        column("username", String),
        column("registered_at", TIMESTAMP),
        column("email", String),
        column("hashed_password", String),
        column("is_active", Boolean),
        column("is_superuser", Boolean),
        column("is_verified", Boolean),
    )

    subscription_table = table(
        "subscription",
        column("subscriber", UUID),
        column("subscribed", UUID),
    )

    op.bulk_insert(
        user_table,
        [
            {
                "id": '00000000-0000-0000-0000-000000000000',
                "name": "echafaud",
                "username": "echafaud",
                "registered_at": datetime.datetime(year=1, month=1, day=1),
                "email": "echafaud0@gmail.com",
                "hashed_password": PasswordHelper().hash(ADMIN_PASSWORD),
                "is_active": False,
                "is_superuser": True,
                "is_verified": True,
            },
        ],
    )
    op.bulk_insert(
        subscription_table,
        [
            {
                "subscriber": '00000000-0000-0000-0000-000000000000',
                "subscribed": '00000000-0000-0000-0000-000000000000',
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
