"""rename author to owner

Revision ID: 515c9c701a14
Revises: a4ecf115abec
Create Date: 2023-06-15 06:15:45.293244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515c9c701a14'
down_revision = 'a4ecf115abec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('comment_author_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['owner_id'], ['id'])
    op.drop_column('comment', 'author_id')
    op.add_column('like', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'user', ['owner_id'], ['id'])
    op.drop_column('like', 'user_id')
    op.add_column('user_view', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_view_author_id_fkey', 'user_view', type_='foreignkey')
    op.create_foreign_key(None, 'user_view', 'user', ['owner_id'], ['id'])
    op.drop_column('user_view', 'author_id')
    op.add_column('video', sa.Column('owner', sa.UUID(), nullable=False))
    op.drop_constraint('video_author_fkey', 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'user', ['owner'], ['id'])
    op.drop_column('video', 'author')
    op.add_column('view', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.drop_constraint('view_author_id_fkey', 'view', type_='foreignkey')
    op.create_foreign_key(None, 'view', 'user', ['owner_id'], ['id'])
    op.drop_column('view', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'view', type_='foreignkey')
    op.create_foreign_key('view_author_id_fkey', 'view', 'user', ['author_id'], ['id'])
    op.drop_column('view', 'owner_id')
    op.add_column('video', sa.Column('author', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key('video_author_fkey', 'video', 'user', ['author'], ['id'])
    op.drop_column('video', 'owner')
    op.add_column('user_view', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_view', type_='foreignkey')
    op.create_foreign_key('user_view_author_id_fkey', 'user_view', 'user', ['author_id'], ['id'])
    op.drop_column('user_view', 'owner_id')
    op.add_column('like', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_user_id_fkey', 'like', 'user', ['user_id'], ['id'])
    op.drop_column('like', 'owner_id')
    op.add_column('comment', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_author_id_fkey', 'comment', 'user', ['author_id'], ['id'])
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###
