"""make nullable author_id in view model

Revision ID: 5c6e365765e8
Revises: 4c872bb3171d
Create Date: 2023-05-28 16:31:20.649747

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c6e365765e8'
down_revision = '4c872bb3171d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'author_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'author_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    # ### end Alembic commands ###
