"""add comment cascade delete

Revision ID: 7e98120060de
Revises: 0570a7e1c080
Create Date: 2023-06-05 20:09:53.122751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e98120060de'
down_revision = '0570a7e1c080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_video_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_video_id_fkey', 'comment', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
