"""add view and user_view cascade delete

Revision ID: 9eab491449bd
Revises: 29e876758f32
Create Date: 2023-06-05 22:10:47.835565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eab491449bd'
down_revision = '29e876758f32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_view_video_id_fkey', 'user_view', type_='foreignkey')
    op.create_foreign_key(None, 'user_view', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('view_video_id_fkey', 'view', type_='foreignkey')
    op.create_foreign_key(None, 'view', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view', type_='foreignkey')
    op.create_foreign_key('view_video_id_fkey', 'view', 'video', ['video_id'], ['id'])
    op.drop_constraint(None, 'user_view', type_='foreignkey')
    op.create_foreign_key('user_view_video_id_fkey', 'user_view', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
