"""rename video ulpoad to uploaded

Revision ID: a4ecf115abec
Revises: 6f0c596cacad
Create Date: 2023-06-15 06:10:55.501640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4ecf115abec'
down_revision = '6f0c596cacad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('video', 'upload_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('upload_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('video', 'uploaded_at')
    # ### end Alembic commands ###
