"""fingerprint nullable true

Revision ID: d35326793118
Revises: 4bd25fb493e7
Create Date: 2023-06-19 01:50:46.175137

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd35326793118'
down_revision = '4bd25fb493e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'fingerprint',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('view', 'fingerprint',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
