"""add view model

Revision ID: e58e12f540d7
Revises: 9ea1e3a04b05
Create Date: 2023-05-24 00:11:36.221715

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e58e12f540d7'
down_revision = '9ea1e3a04b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('author_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('video_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('stop_timecode', postgresql.INTERVAL(), nullable=False),
    sa.Column('viewing_time', postgresql.INTERVAL(), nullable=True),
    sa.Column('viewed_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view')
    # ### end Alembic commands ###
