"""add duration to video vodel and edit max len for title, description and user model name, username

Revision ID: fb9efeef07cc
Revises: 0740ccfde431
Create Date: 2023-06-09 18:48:21.773750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb9efeef07cc'
down_revision = '0740ccfde431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('duration', postgresql.INTERVAL(), nullable=False))
    op.alter_column('video', 'title',
                    existing_type=sa.VARCHAR(length=60),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    op.alter_column('video', 'description',
                    existing_type=sa.VARCHAR(length=340),
                    type_=sa.String(length=5000),
                    existing_nullable=False)
    op.alter_column('user', 'name',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.String(length=64),
                    existing_nullable=False)
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'description',
                    existing_type=sa.String(length=5000),
                    type_=sa.VARCHAR(length=340),
                    existing_nullable=False)
    op.alter_column('video', 'title',
                    existing_type=sa.String(length=100),
                    type_=sa.VARCHAR(length=60),
                    existing_nullable=False)
    op.alter_column('user', 'name',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=30),
                    existing_nullable=False)
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=20),
                    existing_nullable=False)
    op.drop_column('video', 'duration')
    # ### end Alembic commands ###
